# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/shaheed1090@gmail.com/New Pipeline 2025-11-15 20:34")

# COMMAND ----------

/Volumes/inventory/source_data/orders/orders_000.json
